site_name: RoServices Documentation

theme:
  name: material
  features:
    - navigation.footer
    - navigation.top

nav:
    - Home: index.md
    - Getting Started: 
      - Dashboard Setup: Setup/Dashboard.md

    - Template Configuration:
      - Rank Center: Setup/RankCenter.md
      - Application Center: Setup/ApplicationCenter.md

    - API:
      - API Guide: API/APIguide.md
      - Demote: API/Demote.md
      - Promote: API/Promote.md
      - HandleRequest: API/HandleRequest.md
      - SetRank: API/Setrank.md
      - Shout: API/Shout.md
    
    - Discord Bot Examples:
      - Simple d.py bot: BotExamples/dpy.md

plugins:
  - tags
  - search

markdown_extensions:
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - def_list
  - meta
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.com/invite/s8sftcd7uF

copyright: Copyright &copy; 2023 RoServices

